### ISSUE TITLE
Fanstatic Extension

### ISSUE THREAD

**Issue by agronholm** [marrow/WebCore#130]
Add support for the Fanstatic project, which allows dynamically including ECMAScript and other media files in HTML using a dependency system.

**Comment by amcgregor** [comment]
Fantastic doesn't seem to have the Pypi support it claims (old jQuery among other things) and hasn't been updated in a year despite remaining in a an "alpha" state.  I somewhat like the design.

WebAssets has more recent updating and doesn't quite attempt to tackle the same scope of features, and will be implemented first.
